@startmindmap PS-myslenkova_mapa_hlavicka
* Hlavička dokumentu
**_ Identifikace pacienta
***_ Křestní jméno
***_ Příjmení
***_ Datum narození
***_ Identifikátor pacienta
***_ Státní občanství
***_ Úřední pohlaví
***_ Komunikační jazyk
**_ Kontaktní informace pacienta
***_ Adresa
***_ Telekomunikační kontakt e-mail, telefon 
***_ Preferovaný lékař
****_ Identifikátor zdravotnického pracovníka v KRZP
****_ Jméno lékaře
****_ Specializace lékaře
****_ ID a název poskytovatele
****_ Adresa poskytovatele
****_ Telekomunikační kontakt e-mail, telefon 
***_ Zákonní zástupci a další kontaktní osoby
****_ Typ kontaktu
****_ Vztah k pacientovi
****_ Křestní jméno
****_ Příjmení
****_ Adresa kontaktní osoby
****_ Telekomunikační kontakt e-mail, telefon 
**_ Zdravotní pojištění
***_ Kód zdravotní pojišťovny
***_ Název zdravotní pojišťovny
***_ Číslo zdravotního pojištění
**_ Autor dokumentu
***_ Identifikátor autora
***_ Jméno autora
***_ ID organizace
***_ Organizace autora
***_ Datum a čas uložení
**_ Ověřil
***_ Identifikátor ověřovatele
***_ Jméno ověřovatele
***_ ID organizace
***_ Organizace ověřovatele
***_ Datum a čas ověření
**_ Metadata dokumentu
***_ ID dokumentu
***_ Kategorie dokumentu
***_ Datum a čas vytvoření
***_ Název dokumentu
***_ Správce dokumentu
***_ Důvěrnost dokumentu
***_ Jazyk dokumentu
***_ Povaha souhrnu
**_ Elektronické podpisy
***_ Elektronický podpis
***_ Časové razítko
@endmindmap