@startmindmap PS-myslenkova_mapa
* PS
' * [[StructureDefinition-LogCzPSCz.html Pacientký souhrn]]
' ** [[StructureDefinition-LogHeaderPSCz.html Hlavička dokumentu]]
** Tělo dokumentu
' ** [[StructureDefinition-LogPresentedFormCz.html Zobrazitelná forma dokumentu]]
@endmindmap