@startmindmap
* Pacientský souhrn
** Administrativní údaje
** Urgentní informace
** Údaje poskytnuté pacientem
** Informace o zdravotním stavu
** Zdravotní problémy
** Souhrn medikace
** Sociální anamnéza
** Historie těhotenství
** Výsledky
** Plán péče
** Přílohy
@endmindmap