@startuml PS_Alerts-map
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Alerts" <<LogicalModel>> [[StructureDefinition-LogAlertsCzEn.html]]
' note top #PaleTurquoise [[ConceptMap-alerts2FHIR-cz-ps.html]]
' Concept Map
' endnote
' --- Profiles mapping Alerts ---
class "cz-composition-ps" <<Profile>> [[StructureDefinition-cz-composition-ps.html]]
class "cz-allergyIntolerance-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-allergyIntolerance.html]]
class "cz-flag-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-flag-patient-cz-core.html]]

' --- Realization links ---
"Alerts" <|. "cz-composition-ps"
"Alerts" <|. "cz-allergyIntolerance-core"
"Alerts" <|. "cz-flag-core"

' ' (volitelné – skryté vazby jen pro rozložení v diagramu)
"cz-allergyIntolerance-core" -d[hidden]-> "cz-composition-ps"
"cz-composition-ps" -d[hidden]-> "cz-allergyIntolerance-core"
"cz-composition-ps" -d[hidden]-> "cz-flag-core"
@enduml