@startuml PS_Alerts-map
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Alerts" <<LogicalModel>> [[StructureDefinition-LogAlertsCzEn.html]]
note top #PaleTurquoise [[ConceptMap-alerts2FHIR-cz-ps.html]]
Concept Map
endnote
' --- Profiles mapping Alerts ---
class "cz-composition-ps" <<Profile>> [[StructureDefinition-cz-composition-ps.html]]
class "cz-allergyIntolerance-ps" <<Profile>> [[StructureDefinition-cz-allergyIntolerance-ps.html]]
class "cz-flag-ps" <<Profile>> [[StructureDefinition-cz-flag-ps.html]]

' --- Realization links ---
"Alerts" <|. "cz-composition-ps"
"Alerts" <|. "cz-allergyIntolerance-ps"
"Alerts" <|. "cz-flag-ps"

' ' (volitelné – skryté vazby jen pro rozložení v diagramu)
"cz-allergyIntolerance-ps" -d[hidden]-> "cz-composition-ps"
"cz-composition-ps" -d[hidden]-> "cz-allergyIntolerance-ps"
"cz-composition-ps" -d[hidden]-> "cz-flag-ps"
@enduml