@startuml PS_CarePlan-map
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Care Plan" <<LogicalModel>> [[StructureDefinition-LogCarePlanCz.html]]
note top #PaleTurquoise [[ConceptMap-carePlan2FHIR-cz-ps.html]]
Concept Map
endnote
' --- Profiles mapping Alerts ---


' --- Realization links ---


' ' (volitelné – skryté vazby jen pro rozložení v diagramu)

@enduml