@startmindmap
* Hlavička dokumentu
** Identifikace pacienta
*** Křestní jméno
*** Příjmení
*** Datum narození
*** Identifikátor pacienta
*** Státní občanství
*** Úřední pohlaví
*** Komunikační jazyk
** Kontaktní informace pacienta
*** Adresa
*** Telekomunikační kontakt e-mail, telefon 
*** Preferovaný lékař
**** Identifikátor zdravotnického pracovníka v KRZP
**** Jméno lékaře
**** Specializace lékaře
**** ID a název poskytovatele
**** Adresa poskytovatele
**** Telekomunikační kontakt e-mail, telefon 
*** Zákonní zástupci a další kontaktní osoby
**** Typ kontaktu
**** Vztah k pacientovi
**** Křestní jméno
**** Příjmení
**** Adresa kontaktní osoby
**** Telekomunikační kontakt e-mail, telefon 
** Zdravotní pojištění
*** Kód zdravotní pojišťovny
*** Název zdravotní pojišťovny
*** Číslo zdravotního pojištění
** Autor dokumentu
*** Identifikátor autora
*** Jméno autora
*** ID organizace
*** Organizace autora
*** Datum a čas uložení
** Ověřil
*** Identifikátor ověřovatele
*** Jméno ověřovatele
*** ID organizace
*** Organizace ověřovatele
*** Datum a čas ověření
** Metadata dokumentu
*** ID dokumentu
*** Kategorie dokumentu
*** Datum a čas vytvoření
*** Název dokumentu
*** Správce dokumentu
*** Důvěrnost dokumentu
*** Jazyk dokumentu
*** Povaha souhrnu
** Elektronické podpisy
*** Elektronický podpis
*** Časové razítko
@endmindmap