@startmindmap
* Historie těhotenství
** Aktuální těhotenství
*** Datum zápisu
*** Stav
*** Očekávané datum porodu
*** Kód způsobu stanovení těhotenství
** Historie předchozích těhotenství
*** Stav předchozích těhotenství
*** Popis předchozích těhotenství
**** Datum výsledku
**** Výsledek
**** Počet dětí
@endmindmap