@startuml PS_Header-map
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Medical Conditions" <<LogicalModel>> [[StructureDefinition-LogMedicalConditionsPSCz.html]]
note top #PaleTurquoise [[ConceptMap-MedicalConditionsToFHIR-cz-ps.html]]
Concept Map
endnote
class "Medical Conditions" <<LogicalModel>> [[StructureDefinition-LogMedicalConditionsPSCz.html]]
class "cz-condition-ps" <<Profile>> [[StructureDefinition-cz-condition-ps.html]]



"Medical Conditions" <|. "cz-condition-ps"

' "cz-condition-ps" -d[hidden]-> "patient-cz-core"
' "patient-cz-core" -d[hidden]-> "practitionerRole-cz-core"
' "practitionerRole-cz-core" -d[hidden]-> "cz-bundle-ps"
' "cz-bundle-ps" -d[hidden]-> "cz-composition-ps"
' "cz-composition-ps" -d[hidden]-> "Coverage-cz"

@enduml