@startuml PS_MedicationSummary-map
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Medication Summary" <<LogicalModel>> [[StructureDefinition-LogMedicationSummaryCzEn.html]]
' note top #PaleTurquoise [[ConceptMap-medicationSummary2FHIR-cz-ps.html]]
' Concept Map
' endnote
' --- Profiles mapping Alerts ---
class "cz-composition-ps" <<Profile>> [[StructureDefinition-cz-composition-ps.html]]
class "cz-medicationstatement-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-medicationStatement-cz-core.html]]
class "cz-medication-core" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-Medication.html]]

' --- Realization links ---
"Medication Summary" <|. "cz-composition-ps"
"Medication Summary" <|. "cz-medicationstatement-core"
"Medication Summary" <|. "cz-medication-core"

' ' (volitelné – skryté vazby jen pro rozložení v diagramu)
"Medication Summary" -d[hidden]-> "cz-composition-ps"
"cz-composition-ps" -d[hidden]-> "cz-medicationstatement-core"
"cz-composition-ps" -d[hidden]-> "cz-medication-core"
@enduml