@startmindmap
* Údaje poskytnuté pacientem
** Dříve vyslovené přání
*** Datum a čas
*** Typ přání
*** Komentář
*** Dotčený stav
*** Dokument
** Cestovatelská anamnéza
*** Země
*** Období
*** Komentář
@endmindmap
