@startmindmap
* Sociální anamnéza
** Abusus
*** Alkohol
**** Stav
**** Období a množství
**** Komentář
*** Kouření
**** Stav
**** Období a množství
**** Komentář
*** Drogy
**** Stav
**** Období a množství
**** Typ látky
**** Způsob podávání
**** Komentář
*** Závislosti
@endmindmap