@startmindmap
* Souhrn medikace
** Medikace
*** Indikace
*** Kód SUKL
*** Název léčivého přípravku
*** Aktivní látky
*** Síla
*** Forma léčiva
*** Dávkování
*** Cesta podání
*** Období podávání
*** Doporučená doba podávání
*** Zamýšlené použití
@endmindmap