@startmindmap
* Urgentní informace
** Alergie a intolerance
*** Popis alergie
*** Kategorie původce
*** Původce
*** Typ reakce
*** Reakce
*** Riziko
*** Počátek období projevu
*** Konec období projevu
*** Stav
*** Míra jistoty
*** Poslední projev
** Varování
*** Označení varování
*** Onemocnění či stav
*** Specializovaný lékař
*** Komentář
*** Úroveň
*** Období platnosti varování
@endmindmap