Logical: LogCzHealthIssuesCz
Id: LogHealthIssuesCz
Title: "A.2.4 Zdravotní problémy"
Description: "Logický model pro zdravotní problémy v Pacientském souhrnu"

* aktualniZdravotniProblemy 1..* Base "A.2.4.1 Aktuální zdravotní problémy" """Nozologické jednotky (choroby definované jasnou nebo předpokládanou etiologií a patofyziologií), tak klinické syndromy či zatím nezařazené klinicky významné stavy"""
  * popisProblemu 1..1 string "A.2.4.1.1 Popis problému" """Zdravotní stavy, které ovlivňují pacienta a musí být známy zdravotníkovi. Popis volným textem"""
  * kod 0..1 CodeableConcept "A.2.4.1.2 Kód" """Formalizované vyjádření zdravotního problému kódem (klasifikace)."""
  * datumVzniku 1..1 date "A.2.4.1.3 Datum vzniku" """Datum vzniku onemocnění. Přesné nebo přibližné datum."""
  * datumVyreseniCiRemise 0..1 date "A.2.4.1.4 Datum vyřešení či remise" """Datum vyřešení či ustoupení problému do remise. Problémy jejichž klinický stav je "aktivní" nemají tento údaj vyplněn."""
  * okolnostiVyreseni 0..1 string "A.2.4.1.5 Okolnosti vyřešení" """Důvod, pro který se stav problému změnil na neaktivní. Takovým důvodem může být např. chirurgický zákrok, lékařské ošetření apod. Toto pole obsahuje „volný text“, který se uvádí pouze pokud nejsou okolnosti řešení zahrnuty v jiných oblastech PS(výkony, implantáty apod.)"""
  * zavaznost 0..1 CodeableConcept "A.2.4.1.6 Závažnost" """Subjektivní hodnocení závažnosti problému klinikem."""
  * stadiumOnemocneni 0..* CodeableConcept "A.2.4.1.7 Stadium onemocnění" """Stadium/grading problému dle zvolené škály textem a/nebo kódem. Jako výchozí byla zvolena klasifikace TNM - klasifikace zhoubných novotvarů a mezinárodní klasifikace nemocí pro onkologii. Další systémy klasifikace stupně či stadia onemocnění mohou být doplněny dle klinických potřeb a na základě konsensu odborné veřejnosti.""" //TODO: nebude vhodnější kardinalita 0..1?
  * stavPotvrzeniDiagnozy 0..1 Base "A.2.4.1.8 Stav potvrzení diagnózy" """Stadium/grading problému dle zvolené škály textem a/nebo kódem. Jako výchozí byla zvolena klasifikace TNM - klasifikace zhoubných novotvarů a mezinárodní klasifikace nemocí pro onkologii. Další systémy klasifikace stupně či stadia onemocnění mohou být doplněny dle klinických potřeb a na základě konsensu odborné veřejnosti.""" //TODO: jaký zvolit datový typ?
* vykony 1..* Base "A.2.4.2 Výkony" """Podstatné léčebné a diagnosticko-léčebné výkony, tedy nejen chirurgické (laparoskopické i otevřené operace), ale i další endoskopické výkony gastroenterologické, urologické, gynekologické, cévní a další. Hlavním kritériem pro zařazení je význam pro aktuální zdravotní stav i pro budoucí terapeutické i diagnostické procedury."""
  * kodVykonu 0..* CodeableConcept "A.2.4.2.1 Kód výkonu" """Kód výkonu ve zvoleném kódovém systému"""
  * popisProcedury 1..1 string "A.2.4.2.2 Popis procedury" """Popis výkonu volným textem""" //TODO: nepřejemnovat na popis výkonu?
  * lokalizace 0..1 CodeableConcept "A.2.4.2.3 Lokalizace" """Anatomická lokace a strana výkonu s použitím řízené terminologie."""
  * datumProvedeni 1..1 date "A.2.4.2.4 Datum provedení" """Datum provedení výkonu."""
  * duvodProvedeni 0..1 CodeableConcept "A.2.4.2.5 Důvod provedení" """Důvod provedení výkonu textem nebo kódem."""
  * vysledek 0..1 CodeableConcept "A.2.4.2.6 Výsledek" """Formalizované vyjádření výsledku výkonu. Aplikovatelné především na chirurgické výkony."""
  * komplikace 0..* CodeableConcept "A.2.4.2.7 Komplikace" """Komplikace spojené s výkonem (v průběhu či bezprostředně po něm)."""
  * cilovyZdravotnickyProstredek 0..1 Reference "A.2.4.2.8 Cílový zdravotnický prostředek" """Odkaz na zdravotnický prostředek, který byl implantován, odstraněn nebo s ním bylo jinak manipulováno (kalibrace, výměna baterie, nasazení protézy atd.) v průběhu procedury."""
  * pocetProvedeni 0..1 integer "A.2.4.2.9 Počet provedení" """Počet provedení"""
* zdravotniPomuckyAImplantaty 1..* Base "A.2.4.3 Zdravotní pomůcky a implantáty" """Seznam implantovaných a externích zdravotnických prostředků, na kterých je pacient závislý nebo které významně ovlivňují nebo mohou ovlivnit jeho zdravotní stav."""
  * popisZdravotnickehoProstredku 1..1 CodeableConcept "A.2.4.3.1 Popis zdravotnického prostředku" """Popis zdravotnického prostředku (implantovaného či externího) volným textem a/nebo kódem."""
  * identifikatorProstredku 0..* Identifier "A.2.4.3.2 Identifikátor prostředku" """Normalizovaný identifikátor, např. UDI, dle nařízení EU 2017/745"""
  * datumZavedeni 1..1 date "A.2.4.3.3 Datum zavedení" """Datum implantace či počátku užívání zdravotnického prostředku. Může být uvedeno i přibližné datum, pokud přesné datum není známo."""
  * datumOdstraneni 0..1 date "A.2.4.3.4 Datum odstranění" """Datum explantace či ukončení užívání zdravotnického prostředku. Může být uvedeno i přibližné datum, pokud přesné datum není známo."""
  * duvodPouziti 0..1 CodeableConcept "A.2.4.3.5 Důvod použití" """Klinický důvod zavedení či odstranění zdravotnického prostředku vyjádřený textem a/nebo kódem zdravotního problému."""
* funkcniStavy 0..1 Base "A.2.4.4 Funkční stav" """Funkční stav lze hodnotit několika různými způsoby, obvykle se zaměřením na schopnosti osoby vykonávat základní aktivity každodenního života (ADL), které zahrnují základní sebeobsluhu, jako je koupání, krmení a toaleta a instrumentální aktivity každodenního života (IADL), které zahrnují činnosti jako vaření, nakupování a řízení vlastních záležitostí."""
  * datumACas 1..1 dateTime "A.2.4.4.1 Datum a čas" """Datum a čas hodnocení funkčního stavu pacienta."""
  * provedl 0..* Practitioner "A.2.4.4.2 Provedl" """Identifikuje osobu, která  vyšetření provedla nebo je zdrojem informací o výsledku vyšetření. Tato osoba nemusí být totožná s autorem dokumentu."""
  * popis 0..1 string "A.2.4.4.3 Popis" """Textový popis funkčního stavu pacienta"""
  * hodnoceniFormalizovane 0..* Base "A.2.4.4.4	Hodnocení formalizované" """Formalizované hodnocení funkčního stavu pacienta dle jednotlivých hodnotících kategorií zvoleného systému hodnocení (např. MKF)"""
    * datumVzniku 0..1 date "A.2.4.4.4.1 Datum vzniku" """Datum vzniku funkčního omezení"""
    * vysledekVysetreniTextem 0..1 string "A.2.4.4.4.2 Výsledek vyšetření textem" """Výsledek vyšetření volným textem."""
    * popisVysetreni 1..1 CodeableConcept "A.2.4.4.4.3 Popis vyšetření" """Popis vyšetření včetně kódu. Jako výchozí systém pro hodnocení funkčního stavu byl zvolen mezinárodní klasifikační systém MKF. Další typy hodnotících škál mohou být doplněny v budoucích verzích standardu na základě potřeby a konsenzu odborné veřejnosti."""
    * vysledekVysetreniFormalizovane 1..1 CodeableConcept "A.2.4.4.4.4 Výsledek vyšetření formalizovaný" """Výsledek hodnocení funkčního stavu v dané kategorii hodnocení."""