Logical: LogCzAlertsCz
Id: LogAlertsCz
Title: "A.2.2 Urgentní informace"
Description: "Logický model pro urgentní informace v Pacientském souhrnu (Review)"

* alergie 1..* Base "A.2.2.1 - Alergie a intolerance" """Záznam alergie a intolerance je volitelný."""
  * popisAlergie 0..1 string "A.2.2.1.1 - Popis alergie" """Textové doplnění informací volným textem. Je určeno pro zápis informací, které nelze zapsat strukturovaně."""
  * kategoriePuvodce 1..1 CodeableConcept "A.2.2.1.2 - Kategorie původce" """Potravina, léčivom, prostředím, biologikum"""
  * puvodce 1..1 CodeableConcept "A.2.2.1.3 - Původce" """Látka, skupina látek nebo faktor prostředí, na které je pacient alergický nebo přecitlivělý. Původce je možné vyjádřit pomocí kódu substance, ATC skupiny nebo kódu produktu SÚKL (v případě léčivých přípravků)."""
  * puvodce ^comment = "odpovídá ***typ agens*** dle vyhlášky č. 444/2024 Sb."
  * typReakce 0..1 CodeableConcept "A.2.2.1.4 - Typ reakce" """Typ (mechanismus) reakce: alergie, intolerance, nealergická hypersenzitivita."""
  * reakce 0..* CodeableConcept "A.2.2.1.5 - Reakce" """Dosud známé projevy reakce na expozici pacienta původci, textem nebo kódem, včetně možnosti uvést způsob expozice a závažnost projevu."""
  * riziko 0..1 CodeableConcept "A.2.2.1.6 - Riziko" """Stupeň závažnosti je definován jako „potenciální závažnost budoucích reakcí“. Stupeň závažnosti představuje klinické hodnocení nejhoršího scénáře budoucí reakce. Může být založeno na závažnosti minulých reakcí a na stupni ohrožení pacienta."""
  * pocatekObdobiProjevu 0..1 Base "A.2.2.1.7 - Počátek období projevu" """Datum nebo období, ve kterém byla alergie nebo jiná nežádoucí reakce zaznamenána či klinicky stanovena. Může to být přesné datum a čas nebo hrubý údaj o datu (například pouze rok nebo měsíc a rok) nebo vyjádření pomocí kódu věkové fáze (dětství, adolescence apod.), resp. časového intervalu (2001 - 2005 apod.)."""
    * datum 0..1 dateTime "Počátek období projevu - datum" """Datum počátku nežádoucí reakce (např. první výskyt)."""
    * kod 0..1 CodeableConcept "Počátek období projevu - kód" """Vyjádření počátku reakce kódem např. věkové skupiny."""
  * konecObdobiProjevu 0..1 Base "A.2.2.1.8 - Konec období projevu" """Datum nebo období, ve kterém byly projevy alergie nebo jiné nežádoucí reakce potlačeny nebo klinicky vyloučeny."""
  * stav 0..1 CodeableConcept "A.2.2.1.9 - Stav" """„Klinický stav“ vyjadřuje aktuální stav dispozice pacienta k nežádoucí reakci."""
  * miraJistoty 0..1 CodeableConcept "A.2.2.1.10 - Míra jistoty" """Umožňuje vyjádřit míru jistoty zapisujícího lékaře ve vztahu k údajům uvedeným v modelu alergie."""
  * posledniProjev 0..1 dateTime "A.2.2.1.11 - Poslední projev" """Datum (a čas) poslední známé reakce (projevu)."""
* varovani 0..* Base "A.2.2.2 - Varování" """příklady: krvácení po aspirinu, kašel po ACE inhibitoru, přítomnost vzácné nemoci, obtížnou intubaci, transplantovaný orgán, ale také účast v klinické studii"""
  * oznaceniVarovani 0..1 string "A.2.2.2.1 - Označení varování" """Název charakterizující typ či předmět varování"""
  * onemocneniCiStav 0..* CodeableConcept "A.2.2.2.2 - Onemocnění či stav" """Stav či onemocnění, které je zdrojem/příčinou pro varování."""
  * specializovanyLekar 0..* Base "A.2.2.2.3 - Specializovaný lékař" """Kontaktní informace na specialistu, u kterého je pacient v péči - týká se především pacientů se vzácným onemocněním."""
    * jmeno 0..1 HumanName "Jméno specializovaného lékaře"
    * telefon 0..* ContactPoint "Telefonní kontakt na specializovaného lékaře"
    * email 0..* ContactPoint "Emailový kontakt na specializovaného lékaře"
    * adresa 0..1 Address "Adresa pracoviště specializovaného lékaře"
  * komentar 0..1 string "A.2.2.2.4 - Komentář" """Komentář/popis varování volným textem"""
  * uroven 0..1 CodeableConcept "A.2.2.2.5 - Úroveň" """Úroveň závažnosti varování"""
  * obdobiPlatnostiVarovani 0..1 Base "A.2.2.2.6 - Období platnosti varování" """Umožňuje vyjádřit období ve kterém bylo varování aktivní. Týká se přechodných stavů."""
    * datumOd 0..1 dateTime "Období platnosti varování - datum od" """Datum (a čas) začátku platnosti varování."""
    * datumDo 0..1 dateTime "Období platnosti varování - datum do" """Datum (a čas) konce platnosti varování."""