Logical: LogCzHealthIssuesEn
Id: LogHealthIssuesCzEn
Title: "A.2.4 Health Issues"
Description: """A.2.4 Health Issues - Logical model for health issues in the Patient Summary."""

* problems 1..* Base "A.2.4.1 Current health problems" """Nosological entities (diseases with defined or presumed etiology and pathophysiology), as well as clinical syndromes or other clinically significant conditions not yet classified."""
  * description 1..1 string "A.2.4.1.1 Problem description" """Health conditions affecting the patient that must be known to the healthcare professional. Free-text description."""
  * code 0..1 CodeableConcept "A.2.4.1.2 Code" """Formal coded representation of the health problem (classification)."""
  * onsetDate 1..1 date "A.2.4.1.3 Date of onset" """Date of disease onset. Exact or approximate date."""
  * abatementDate 0..1 date "A.2.4.1.4 Date of resolution or remission" """Date when the problem was resolved or went into remission. Problems with an 'active' clinical status do not have this element populated."""
  * abatementReason 0..1 string "A.2.4.1.5 Circumstances of resolution" """Reason why the problem status changed to inactive (e.g., surgical procedure, medical treatment). Used only if not documented elsewhere in the Patient Summary."""
  * severity 0..1 CodeableConcept "A.2.4.1.6 Severity" """Clinician’s subjective assessment of the severity of the problem."""
  * stage 0..* CodeableConcept "A.2.4.1.7 Disease stage" """Stage or grading of the disease expressed as text and/or code according to the selected scale (e.g., TNM, ICD-O)."""
  * verificationStatus 0..1 CodeableConcept "A.2.4.1.8 Diagnosis confirmation status" """Status of diagnostic confirmation (e.g., suspected, provisional, confirmed)."""

* procedure 1..* Base "A.2.4.2 Procedures" """Relevant therapeutic and diagnostic or diagnostic-therapeutic procedures with impact on current or future care."""
  * code 0..* CodeableConcept "A.2.4.2.1 Procedure code" """Procedure code in the selected coding system."""
  * description 1..1 string "A.2.4.2.2 Procedure description" """Free-text description of the """
  * bodySite 0..1 CodeableConcept "A.2.4.2.3 Body site" """Anatomical location and laterality of the procedure using controlled terminology."""
  * performedDate 1..1 date "A.2.4.2.4 Date performed" """Date when the procedure was performed."""
  * reasonCode 0..1 CodeableConcept "A.2.4.2.5 Reason" """Reason for performing the procedure, expressed as text or code."""
  * outcome 0..1 CodeableConcept "A.2.4.2.6 Outcome" """Formal coded representation of the procedure outcome."""
  * complication 0..* CodeableConcept "A.2.4.2.7 Complication" """Complications associated with the procedure."""
  * usedDevice 0..1 Reference "A.2.4.2.8 Target medical device" """Reference to a medical device that was implanted, removed, or otherwise manipulated during the procedure."""
  * performedQuantity 0..1 integer "A.2.4.2.9 Number of occurrences" """Number of times the procedure was performed."""

* device 1..* Base "A.2.4.3 Medical devices and implants" """Implanted or external medical devices on which the patient depends or which significantly affect the health status."""
  * code 1..1 CodeableConcept "A.2.4.3.1 Medical device" """Coded and/or textual description of the medical device (implanted or external)."""
  * identifier 0..* Identifier "A.2.4.3.2 Device identifier" """Normalized identifier (e.g., UDI) according to Regulation (EU) 2017/745."""
  * useStartDate 1..1 date "A.2.4.3.3 Implantation / start of use date" """Date of implantation or start of device use (exact or approximate)."""
  * useEndDate 0..1 date "A.2.4.3.4 Explantation / end of use date" """Date of explantation or end of device use (exact or approximate)."""
  * reasonCode 0..1 CodeableConcept "A.2.4.3.5 Reason" """Clinical reason for implantation or removal of the medical device (text and/or code)."""

* functionalStatus 0..1 Base "A.2.4.4 Functional status" """Assessment of the patient’s ability to perform activities of daily living (ADL) and instrumental activities of daily living (IADL)."""
  * effectiveDateTime 1..1 dateTime "A.2.4.4.1 Date and time" """Date and time of the functional status assessment."""
  * performer 0..* Practitioner "A.2.4.4.2 Assessed by" """Person who performed the assessment or is the source of the information."""
  * note 0..1 string "A.2.4.4.3 Description" """Free-text description of the patient’s functional status."""
  * assessment 0..* Base "A.2.4.4.4 Formal assessment" """Formalized functional status assessment according to a selected evaluation system (e.g., ICF)."""
    * onsetDate 0..1 date "A.2.4.4.4.1 Date of onset" """Date when the functional limitation began."""
    * valueText 0..1 string "A.2.4.4.4.2 Assessment result (text)" """Assessment result expressed as free text."""
    * code 1..1 CodeableConcept "A.2.4.4.4.3 Assessment description" """Assessment description including code (default system: ICF)."""
    * valueCodeableConcept 1..1 CodeableConcept "A.2.4.4.4.4 Assessment result (coded)" """Coded result of the functional status assessment."""